services:
  asas-be:
    container_name: asas-be
    build:
      context: .
      dockerfile: Dockerfile
    # image: bwbayu/asas-be:latest
    expose:
      - 8080
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 60s
      timeout: 5s
      retries: 5
    env_file:
      - .env